DROP TYPE IF EXISTS category;
CREATE TYPE category AS ENUM (
    'Paint color',
    'Flooring',
    'Appliances',
    'Cabinets',
    'Lighting',
    'Furniture',
    'Misc',
    'Counters',
    'Inspiration',
    'Decor',
    'Doors',
    'Fireplace'
);

DROP TYPE IF EXISTS room;
CREATE TYPE room AS ENUM (
    'Living Room',
    'Kitchen',
    'Master Bedroom',
    'Guest Bedroom',
    'Kids Bedroom',
    'Master Bathroom',
    'Guest Bathroom',
    'Kids Bathroom',
    'Office',
    'Bonus Room',
    'Mud + Laundry Room',
    'Basement'
);


CREATE TABLE visions (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  vision_image VARCHAR(2000) NOT NULL,
  vision_category category  NOT NULL,
  vision_room room NOT NULL,
  note TEXT,
  link VARCHAR(3000)
);
